### PR TITLE
Improve features for background checks

### LINKED ISSUE #39: [VERY HIGH] Existing User able to Request New Checkr Background Check so Linked to their User Account
1. As of now, there is nothing in place where an existing SDRT User can request a personalized background check from Checkr so that their User Account Role will automatically update from "Volunteer Pending" to "Volunteer" when their background check clears. Thinking this would look like the Existing User being able to start a new background check from Profile page. 

2. In the past we have sent Returning Tutors/Existing Users a SDRT general Checkr link, not something that is specifically linked to their account. Whether an Existing Tutor had completed a new yearly background check was kept track of manually.

### PR DESCRIPTION
**Pull request by JasonTheAdams**
Resolves #39 

This PR adds three features surrounding the improvement to the annual flow of background checks:

### 1. Clear background checks
Admins and SDRT Leadership have a new bulk action when viewing the Users table to clear a volunteer's background check:
Image 2021-07-31 at 10 08 25 PM

The "Background Check" has been added to the Users table for clarity. Once a volunteer has been cleared, their Background Check status will go to "Cleared".

### 2. Cleared volunteer requests new background check
Volunteers that have been cleared from a previous year will see a new screen when viewing their profile:
Image 2021-07-31 at 10 07 53 PM

Using the new button, the volunteer may request a new background check to be triggered. Once the background check has been triggered, the volunteer will see a new message:
Image 2021-07-31 at 10 08 04 PM

### 3. Admin request background check

Admins and SDRT Leadership may also trigger a new background check for volunteers, if that volunteer is missing either a candidate id or invitation url:
Image 2021-07-31 at 10 08 51 PM

---

**Notes on Background Checks**
1. When a volunteer is cleared from a previous year, the invitation url is cleared, but not the candidate id. The reason for this is that the candidate id will be reused for the next check.
2. The system is smart enough to handle the candidate id and/or the invitation url missing. So if a volunteer somehow gets in a strange state, the system should be able to recover when the request is made.
3. If for some reason there's an issue with a volunteer's invitation url, just clear the user with the batch action and request a new background check.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@mathetos Can you please look over the copy for this?

@dreazee Does this tick all the boxes for the desired background check flow?

**Comment by mathetos** [comment]
Love it @JasonTheAdams This looks perfect.

**Comment by dreazee** [comment]
@JasonTheAdams This seems to be exactly what is needed! When will this functionality be implemented? I see that it has not been pushed through just yet. Let me know!

**Comment by JasonTheAdams** [comment]
Awesome! Thanks for the feedback! I'll go ahead and deploy this tomorrow!

I would deploy this to staging, but I'm afraid this is hard to test without using live Checkr credentials. I did use the test credentials locally, but it would just look like it's working in the admin-side without sending any emails or anything.

**Comment by dreazee** [comment]
Okay great! I will take a look at it. I registered my alias so can test it out on my alternate profile/email address :)

**Comment by dreazee** [comment]
@JasonTheAdams Soooo... Is there a way to UNCLEAR Background checks?? I accidentally implemented the function "Clear Background Check" for a bunch of Minors (those under 18 years old would fill out a Minors Registration Form, and NOT request a background check)... Not a big deal since they are Returning Tutors and I can address that, but wanted to check to see if there was a way I can reverse that function.

**Comment by JasonTheAdams** [comment]
Hahah! Accidents happen. I'm afraid there isn't a bulk way to reverse that, but you can manually set the Background Check status for users from the Edit User page:
Image 2021-09-16 at 7 09 53 PM

**Comment by dreazee** [comment]
@JasonTheAdams  Oh yes, I know this - I have to manually change the background check status... this Volunteer Requirement function isn't tied in automatically with Checkr, unfortunately. (is that something that *could be* automatic? You know what, I will address in a separate Github thread.")

Let me explain previous issue better, though: 
Minors do not have a background check since they are under 18; they fill out a separate "Minors Registration Form" instead.
To "Clear" the Background Check Requirement adds that option for Users to "Request Background Check" from their Profile Page. Minors shouldn't have that "Request Background Check" option show up on their Profile Page. So I was looking for a way to reverse that. It's fine since they won't be able to actually pay for a background check since they are under age, but it is confusing. I am going to address this more in a separate Github issue, too, with the idea of greater automation in mind.

**Pull request merged**
